In [1]:
import numpy as np

In [2]:
np.add(1.0, 3.0)

4.0

In [3]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([2, 2, 2, 2, 2])

In [4]:
a + b

array([3, 4, 5, 6, 7])

In [5]:
np.add(a, b)

array([3, 4, 5, 6, 7])

In [6]:
a%b

array([1, 0, 1, 0, 1])

In [7]:
c = np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
d = 3

In [9]:
c*d

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [10]:
e = np.random.randint(1, 10, 20).reshape(2,10)
e

array([[2, 3, 2, 7, 8, 9, 3, 1, 4, 3],
       [6, 9, 6, 6, 1, 5, 2, 3, 7, 4]])

In [11]:
c + e

array([[ 2,  4,  4, 10, 12, 14,  9,  8, 12, 12],
       [ 6, 10,  8,  9,  5, 10,  8, 10, 15, 13]])

In [12]:
e.sum

<function ndarray.sum>

In [13]:
e.sum()

91

In [14]:
np.sum(e, axis = 1)

array([42, 49])

In [15]:
np.sum(e, axis = 2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [16]:
np.power(2, 3)

8

In [17]:
2**3

8

In [18]:
np.power(a,b)

array([ 1,  4,  9, 16, 25])

In [19]:
np.sqrt(4)

2.0

In [20]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [21]:
np.e

2.718281828459045

In [22]:
np.exp(1)

2.718281828459045